In [692]:
import pandas as pd
from pathlib import Path
import numpy as np
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
from sklearn.utils.class_weight import compute_sample_weight

## Configuration

In [693]:
RANDOM_STATE=42
ROOT_DIR = Path().cwd().parent
DATASET_DIR = ROOT_DIR / "dataset"
CSV_FILE_PATH = Path.joinpath(DATASET_DIR,"processed","classification_athlete_events.csv")
print(ROOT_DIR,"\n",DATASET_DIR,"\n",CSV_FILE_PATH)

/home/mdev/Documents/ml/olympic_medals_prediction
 /home/mdev/Documents/ml/olympic_medals_prediction/dataset
 /home/mdev/Documents/ml/olympic_medals_prediction/dataset/processed/classification_athlete_events.csv

## Load dataset and modify

In [694]:
df = pd.read_csv(CSV_FILE_PATH)
df.head()

,noc,season,year,athletes,athletes_female_percentage,avg_age,agv_height,avg_weight,prev_medals,prev_gold_medals,sports,events,total_medals,km_cluster,ag_cluster
0,CHN,1,1932,1,0.000000,22.0,175.0,70.0,0.0,0.0,1,2,0,0,0
1,CHN,1,1936,54,0.037037,24.0,175.0,69.0,0.0,0.0,7,27,0,0,0
2,CHN,1,1948,31,0.032258,26.0,175.0,70.0,0.0,0.0,6,12,0,0,0
3,CHN,1,1952,1,0.000000,23.0,175.0,70.0,0.0,0.0,1,1,0,0,0
4,CHN,1,1984,215,0.386047,23.0,173.0,66.0,0.0,0.0,19,105,32,0,0

In [695]:
df = df.drop(columns=['athletes_female_percentage','ag_cluster'])
df = df.rename(columns={'km_cluster':'label'})
df.head()

,noc,season,year,athletes,avg_age,agv_height,avg_weight,prev_medals,prev_gold_medals,sports,events,total_medals,label
0,CHN,1,1932,1,22.0,175.0,70.0,0.0,0.0,1,2,0,0
1,CHN,1,1936,54,24.0,175.0,69.0,0.0,0.0,7,27,0,0
2,CHN,1,1948,31,26.0,175.0,70.0,0.0,0.0,6,12,0,0
3,CHN,1,1952,1,23.0,175.0,70.0,0.0,0.0,1,1,0,0
4,CHN,1,1984,215,23.0,173.0,66.0,0.0,0.0,19,105,32,0

## Class ratio

In [696]:
class_ratio = df['label'].value_counts(normalize=True)
class_ratio

label
0    0.898358
1    0.089393
2    0.012249
Name: proportion, dtype: float64

In [697]:
df[df['label'] == 0]

,noc,season,year,athletes,avg_age,agv_height,avg_weight,prev_medals,prev_gold_medals,sports,events,total_medals,label
0,CHN,1,1932,1,22.0,175.0,70.0,0.0,0.0,1,2,0,0
1,CHN,1,1936,54,24.0,175.0,69.0,0.0,0.0,7,27,0,0
2,CHN,1,1948,31,26.0,175.0,70.0,0.0,0.0,6,12,0,0
3,CHN,1,1952,1,23.0,175.0,70.0,0.0,0.0,1,1,0,0
4,CHN,1,1984,215,23.0,173.0,66.0,0.0,0.0,19,105,32,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3832,MNE,0,2014,2,19.0,180.0,73.0,0.0,0.0,1,3,0,0
3833,ALB,0,2006,1,19.0,180.0,74.0,0.0,0.0,1,3,0,0
3834,ALB,0,2010,1,23.0,180.0,74.0,0.0,0.0,1,2,0,0
3835,ALB,0,2014,1,20.0,163.0,56.0,0.0,0.0,1,2,0,0
3836,SWZ,0,1992,1,24.0,175.0,70.0,0.0,0.0,1,3,0,0

## Split dataset into train,test

In [698]:
X = df.drop(columns=['noc','label','prev_medals','prev_gold_medals','total_medals'])
y = df['label']
X.head()

   season  year  athletes  avg_age  agv_height  avg_weight  sports  events
0       1  1932         1     22.0       175.0        70.0       1       2
1       1  1936        54     24.0       175.0        69.0       7      27
2       1  1948        31     26.0       175.0        70.0       6      12
3       1  1952         1     23.0       175.0        70.0       1       1
4       1  1984       215     23.0       173.0        66.0      19     105

In [699]:
y

0       0
1       0
2       0
3       0
4       0
       ..
3832    0
3833    0
3834    0
3835    0
3836    0
Name: label, Length: 3837, dtype: int64

In [700]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=RANDOM_STATE,stratify=y)

In [701]:
train,test = train_test_split(X,test_size=0.2,random_state=RANDOM_STATE)

## Scaling for logistic regression only

In [702]:
scaler = RobustScaler()

In [703]:
print(train.head())
print(test.head())

      season  year  athletes  avg_age  agv_height  avg_weight  sports  events
433        1  1920        47     25.0       176.0        71.0       8      34
1569       1  1960        65     28.0       172.0        71.0      11      52
371        1  2000       435     26.0       178.0        72.0      30     238
3148       0  1984        99     25.0       175.0        72.0      10      38
2298       1  1912         2     19.0       172.0        65.0       1       2
      season  year  athletes  avg_age  agv_height  avg_weight  sports  events
1113       1  2008         5     24.0       177.0        70.0       3       5
1309       1  2008        21     25.0       179.0        73.0       5       7
805        1  1920        39     29.0       176.0        70.0       7      34
1173       1  1968       226     25.0       175.0        70.0      18     124
2770       1  1996         6     23.0       173.0        67.0       4       6

In [704]:
exclude_cols = ['season']
to_scale_cols = [ x for x in train.columns.tolist() if x not in exclude_cols ]
to_scale_cols

['year', 'athletes', 'avg_age', 'agv_height', 'avg_weight', 'sports', 'events']

In [705]:
train[to_scale_cols] = scaler.fit_transform(train[to_scale_cols])
test[to_scale_cols] = scaler.transform(test[to_scale_cols])

In [706]:
print(train.head())
print(test.head())

      season      year  athletes   avg_age  agv_height  avg_weight  sports  \
433        1 -2.000000  0.653061  0.000000        0.25    0.166667   0.375
1569       1 -0.888889  1.020408  1.000000       -0.75    0.166667   0.750
371        1  0.222222  8.571429  0.333333        0.75    0.333333   3.125
3148       0 -0.222222  1.714286  0.000000        0.00    0.333333   0.625
2298       1 -2.222222 -0.265306 -2.000000       -0.75   -0.833333  -0.500

        events
433   0.733333
1569  1.333333
371   7.533333
3148  0.866667
2298 -0.333333
      season      year  athletes   avg_age  agv_height  avg_weight  sports  \
1113       1  0.444444 -0.204082 -0.333333        0.50         0.0  -0.250
1309       1  0.444444  0.122449  0.000000        1.00         0.5   0.000
805        1 -2.000000  0.489796  1.333333        0.25         0.0   0.250
1173       1 -0.666667  4.306122  0.000000        0.00         0.0   1.625
2770       1  0.111111 -0.183673 -0.666667       -0.50        -0.5  -0.125

        events
1113 -0.233333
1309 -0.166667
805   0.733333
1173  3.733333
2770 -0.200000

In [707]:
t_train,t_test = train_test_split(y,test_size=0.2,random_state=RANDOM_STATE)

## Model training

In [708]:
lr = LogisticRegression(max_iter=1000,random_state=RANDOM_STATE,class_weight="balanced")
lr.fit(train,t_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [709]:
sample_weights = compute_sample_weight(class_weight="balanced",y=y_train)

In [710]:
xgb = XGBClassifier(
    n_estimators=1000,
    max_depth=8,
    learning_rate=0.1,
    random_state=RANDOM_STATE
)
xgb.fit(X_train,y_train,sample_weight=sample_weights)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1000,
              n_jobs=None, num_parallel_tree=None, ...)

In [711]:
rf = RandomForestClassifier(random_state=RANDOM_STATE,n_estimators=500,class_weight="balanced",max_depth=8)
rf.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', max_depth=8, n_estimators=500,
                       random_state=42)

## Model Predictions

In [712]:
y_pred = xgb.predict(X_test)
y_pred[:15]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0])

In [713]:
rf_pred = rf.predict(X_test)
rf_pred[:15]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0])

In [714]:
lr_pred = lr.predict(test)
lr_pred[:15]

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 1])

In [715]:
def print_metrics(name, y_true, y_pred):
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average="macro")
    rec = recall_score(y_true, y_pred, average="macro")
    f1 = f1_score(y_true, y_pred, average="macro")
    print(f"\n{name} Performance:")
    print(f"  Accuracy : {acc:.3f}")
    print(f"  Precision: {prec:.3f}")
    print(f"  Recall   : {rec:.3f}")
    print(f"  F1-Score : {f1:.3f}")

In [716]:
print_metrics("XGboost",y_test, y_pred)
print_metrics("Random forest",y_test, rf_pred)
print_metrics("Logistic regression",t_test, lr_pred)

XGboost Performance:
  Accuracy : 0.947
  Precision: 0.757
  Recall   : 0.696
  F1-Score : 0.713

Random forest Performance:
  Accuracy : 0.911
  Precision: 0.709
  Recall   : 0.790
  F1-Score : 0.731

Logistic regression Performance:
  Accuracy : 0.889
  Precision: 0.572
  Recall   : 0.827
  F1-Score : 0.640

In [720]:
X_test['y_true'] = y_test.astype(int)
X_test['y_pred'] = y_pred.astype(int)
X_test['right'] = np.where(X_test['y_true'] == X_test['y_pred'], 'Yes', 'No')
X_test.head()

,season,year,athletes,avg_age,agv_height,avg_weight,sports,events,y_true,y_pred,right
1315,1,1968,39,25.0,174.0,66.0,4,22,0,0,Yes
3610,0,2002,4,24.0,169.0,64.0,2,4,0,0,Yes
521,1,1952,64,26.0,175.0,71.0,13,35,0,0,Yes
1469,1,1968,18,28.0,171.0,70.0,6,18,0,0,Yes
1756,1,2012,11,25.0,172.0,63.0,7,10,0,0,Yes

In [721]:
print(X_test['right'].value_counts(normalize=True))

right
Yes    0.946615
No     0.053385
Name: proportion, dtype: float64

In [722]:
mistakes = X_test[X_test['right'] == 'No']
mistakes

,season,year,athletes,avg_age,agv_height,avg_weight,sports,events,y_true,y_pred,right
102,1,1932,40,26.0,175.0,69.0,5,36,1,0,No
737,1,1948,127,26.0,176.0,71.0,13,83,0,1,No
75,1,1924,299,27.0,176.0,71.0,18,108,2,1,No
3585,0,2014,87,28.0,178.0,72.0,13,65,0,1,No
1094,1,1976,213,25.0,169.0,64.0,20,119,1,0,No
3052,0,1994,113,25.0,175.0,71.0,12,56,0,1,No
415,1,1996,164,26.0,179.0,77.0,15,84,1,0,No
3042,0,1998,113,27.0,175.0,73.0,13,54,1,0,No
882,1,1948,152,29.0,176.0,71.0,17,77,0,1,No
99,1,1920,63,32.0,176.0,72.0,9,51,1,0,No
78,1,1936,359,28.0,177.0,71.0,21,127,2,1,No
1168,1,1968,275,25.0,177.0,73.0,17,154,0,2,No
3584,0,2010,90,27.0,178.0,73.0,13,59,0,1,No
1337,1,1996,231,25.0,175.0,71.0,21,148,0,1,No
185,1,1904,1,24.0,175.0,70.0,1,2,2,0,No
1558,1,2012,178,27.0,179.0,74.0,16,87,0,1,No
879,1,1928,187,27.0,176.0,71.0,15,90,0,1,No
72,1,1908,122,27.0,179.0,74.0,10,52,1,0,No
133,1,1952,102,30.0,176.0,71.0,14,72,0,1,No
743,1,1972,208,24.0,176.0,70.0,18,136,0,1,No
9,1,2004,383,23.0,173.0,67.0,31,204,2,1,No
1466,1,2016,234,28.0,181.0,76.0,24,144,0,1,No
543,1,1972,371,25.0,176.0,73.0,22,180,2,1,No
2899,0,1932,19,26.0,176.0,70.0,5,9,1,0,No
399,1,2016,215,28.0,179.0,76.0,26,80,0,1,No
710,1,1906,49,26.0,177.0,72.0,9,41,1,0,No
881,1,1936,150,31.0,175.0,70.0,15,72,0,1,No
163,1,1988,68,22.0,168.0,64.0,10,59,1,0,No
2896,0,2014,99,27.0,176.0,70.0,9,41,0,1,No
450,1,1996,121,23.0,173.0,69.0,18,94,0,1,No
1453,1,1960,185,26.0,173.0,69.0,17,108,0,1,No
316,1,1932,112,27.0,171.0,70.0,13,61,1,0,No
188,1,1912,119,31.0,175.0,71.0,13,66,1,0,No
2893,0,2002,98,26.0,176.0,71.0,11,41,0,1,No
2868,0,1992,148,26.0,175.0,72.0,12,56,0,1,No
300,1,1992,138,23.0,172.0,67.0,19,116,1,0,No
545,1,1980,489,24.0,177.0,73.0,23,202,2,1,No
299,1,1988,172,24.0,174.0,69.0,16,120,0,1,No
1093,1,1972,184,25.0,170.0,65.0,21,113,1,0,No
428,1,1900,3,25.0,175.0,70.0,2,3,1,0,No
1240,1,1912,444,27.0,176.0,71.0,16,95,1,2,No