In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
from sklearn.preprocessing import RobustScaler

## Configuration

In [3]:
RANDOM_STATE=42
ROOT_DIR = Path().cwd().parent
DATASET_DIR = ROOT_DIR / "dataset"
CSV_FILE_PATH = Path.joinpath(DATASET_DIR,"processed","classification_athlete_events.csv")
print(ROOT_DIR,"\n",DATASET_DIR,"\n",CSV_FILE_PATH)

/home/mdev/Documents/ml/olympic_medals_prediction
 /home/mdev/Documents/ml/olympic_medals_prediction/dataset
 /home/mdev/Documents/ml/olympic_medals_prediction/dataset/processed/classification_athlete_events.csv

## Load dataset and modify

In [4]:
df = pd.read_csv(CSV_FILE_PATH)
df.head()

,noc,season,year,athletes,athletes_female_percentage,avg_age,agv_height,avg_weight,prev_medals,prev_gold_medals,sports,events,total_medals,km_cluster,ag_cluster
0,CHN,1,1932,1,0.000000,22.0,175.0,70.0,0.0,0.0,1,2,0,0,0
1,CHN,1,1936,54,0.037037,24.0,175.0,69.0,0.0,0.0,7,27,0,0,0
2,CHN,1,1948,31,0.032258,26.0,175.0,70.0,0.0,0.0,6,12,0,0,0
3,CHN,1,1952,1,0.000000,23.0,175.0,70.0,0.0,0.0,1,1,0,0,0
4,CHN,1,1984,215,0.386047,23.0,173.0,66.0,0.0,0.0,19,105,32,0,0

In [5]:
df = df.drop(columns=['athletes_female_percentage','ag_cluster'])
df = df.rename(columns={'km_cluster':'label'})
df.head()

,noc,season,year,athletes,avg_age,agv_height,avg_weight,prev_medals,prev_gold_medals,sports,events,total_medals,label
0,CHN,1,1932,1,22.0,175.0,70.0,0.0,0.0,1,2,0,0
1,CHN,1,1936,54,24.0,175.0,69.0,0.0,0.0,7,27,0,0
2,CHN,1,1948,31,26.0,175.0,70.0,0.0,0.0,6,12,0,0
3,CHN,1,1952,1,23.0,175.0,70.0,0.0,0.0,1,1,0,0
4,CHN,1,1984,215,23.0,173.0,66.0,0.0,0.0,19,105,32,0